version: '3'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: mongodb+srv://pokemondb_user:espass123@pokemoncluster.wrceebq.mongodb.net/nest-pokemon
    volumes:
      - ./mongo:/data/db
